
services:
#   spring 어플리케이션 이미지
#  app:
#    image: mildo7/codefarm-actions-test:latest
#    container_name: spring-app
#    ports:
#      - "8080:8080"
#    depends_on:
#      - redis

# redis 서버 이미지
  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6379:6379"

# postgres 이미지
  postgres:
    image: postgres:latest
    container_name: postgres-server
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:


#  volumes 을 사용하면 데이터베이스 의 데이터를 영구적으로 저장할 수 있다.
#  Docker 컨테이너가 종료되거나 삭제되면 그 내부의 데이터가 사라집니다

