version: '3.9'

services:
  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6379:6379"
      -
#  postgres:
#    image: postgres:latest
#    environment:
#      POSTGRES_USER: ${DB_USERNAME}
#      POSTGRES_PASSWORD: ${DB_PASSWORD}
#      POSTGRES_DB: ${DB_NAME}
#    ports:
#      - "5432:5432"
#    volumes:
#      - db-data:/var/lib/postgresql/data
#
#  app:
#    image: farm-spring-image
#    environment:
#      SPRING_DATASOURCE_URL: ${DB_URL}
#      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
#      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
#    depends_on:
#      - postgres
#    ports:
#      - "8080:8080"

#  volumes 을 사용하면 데이터베이스 의 데이터를 영구적으로 저장할 수 있다.
#  Docker 컨테이너가 종료되거나 삭제되면 그 내부의 데이터가 사라집니다
volumes:
  db-data:

