#spring.application.name=farm
spring:
  datasource:
  url: ${DB_URL}
  username: ${DB_USERNAME}
  password: ${DB_PASSWORD}
  driver-class-name: org.postgresql.Driver

  data:
    redis:
      port: ${REDIS_PORT}
      host: ${REDIS_HOST}

